### ISSUE TITLE
Publication of the source code of the Vaccination Certificate Service

### ISSUE THREAD

**Issue by Blixary** [Digitaler-Impfnachweis/documentation#11] opened 2021-06-10 13:47 UTC
It has been announced that the complete source code of the Digital Immunisation Record will be published upon release. The same is claimed on the website, where the Digital Certificate of Vaccination is described as an "open source project of the Robert Koch Institute". 

On GitHub, however, only documentation and the APIs for checking the certificates have been put online so far. The system for creating the vaccination certificates, the "Impfzertifikatsservice" has not yet been published.

It would be nice if you would also publish this part of the project as the most important one together with the apps for the different operating systems as soon as possible.

**Comment by Art4** [comment] 2021-06-11 08:16
Duplicate of #6.

**Comment by TilmanJimenez** [comment] 2021-06-11 13:07
> Duplicate of #6.
I disagree. #6 asks for the source code of the app. This one is mainly about the code used for signing. This is the most interesting part from a security point.

**Comment by thinkberg** [comment] 2021-06-11 20:59
Its coming, our stuff is open source anyway: [github.com/ubirch](https://github.com/ubirch).  It will be consolidated as a fork here probably.

**Comment by Blixary** [comment] 2021-06-12 06:12
> 
> 
> Its coming, our stuff is open source anyway: [github.com/ubirch](https://github.com/ubirch). It will be consolidated as a fork here probably.

Thank you for the information. 
Please send us the links to the repositories, especially the one to the Impfzertifikatsservice, as soon as they are published/forked.

**Comment by Blixary** [comment] 2021-06-19 20:56
Eight days have passed and the vaccination certificate service has still not been published in this project. If it already exists as a repository of Ubirch GmbH, I still ask for a link to the repo.

**Comment by oliver-steinbrecher** [comment] 2021-09-29 11:46
The open source approach is meant to embrace the apps. We're going to improve the documentation.

**Closed by oliver-steinbrecher** 2021-09-29 11:46 UTC
Labels: general request

**Comment by Blixary** [comment] 2021-09-29 15:14
> 
> 
> The open source approach is meant to embrace the apps. We're going to improve the documentation.

Why should the source code of the vaccination certificate service not be published? A half open source approach does not bring transparency here at all. This decision is completely unacceptable and disappointing.

**Comment by rugk** [comment] 2021-09-29 18:39
Also note that CWA etc. also publish the source code of their server components.

**Comment by stefan-it** [comment] 2022-02-03 16:26
Hi :)

a lot of people are interested in the current progress (and in the code of the vaccination certificate service), see e.g. [this request](https://fragdenstaat.de/anfrage/dokumente-zur-impfzertifikatschnittstelle/), so it would be great if the issue can be re-opened (/cc @oliver-steinbrecher ) as it seems to be not 100% solved.
