### ISSUE TITLE
Release the Android apps via F-Droid and on GitHub

### ISSUE THREAD

**Issue by codejus** [Digitaler-Impfnachweis/documentation#8] opened 2021-06-10 12:37 UTC
As the CWA Fork [CCTG](https://codeberg.org/corona-contact-tracing-germany/cwa-android) has shown there is demand for an alternative distribution way beside the classical App stores. Especially if you have a non german Google Account linked and thus not able to download the app or use an alternative ROM on your android device.

Also for security sensible people the Reproducible Builds F-Droid offers would bring an extra level of trust after you released the Source as promised on the website.

As the Swiss Vaccination Pass apps (Compliant to the EU Covis Digital Pass) are able to be released via F-Droid in general, see [Issue #40 Covid Certificate Android](https://github.com/admin-ch/CovidCertificate-App-Android/issues/40), I except the same for the German apps as there should be no need for a proprietary components like it is the case at the CWA. 

If you need help with the release on F-Droid I think the community would be eager to help you with this.

In addition you can also release the APKs directly her on GitHub like the EU  and Swiss ones are: [EU Covid Pass Verifier App](https://github.com/eu-digital-green-certificates/dgca-verifier-app-android/releases), [EU Covid Pass Wallet App](https://github.com/eu-digital-green-certificates/dgca-wallet-app-android/releases) and [Swiss Apps](https://github.com/admin-ch/CovidCertificate-App-Android/releases)

**Comment by cookiengineer** [comment] 2021-06-10 13:14
I would prefer that the Source Code is validate-able by other means than "blindly" trusting the RKI.

Why are the source codes of the Apps themselves not published?

**Comment by codejus** [comment] 2021-06-10 13:19
I completely agree with you @cookiengineer. Otherwise an F-Droid and APK release is uselesse. Publishing the Source Code is covered in #6 btw.

**Comment by jugendhacker** [comment] 2021-06-12 09:15
@codejus without public source a release in the official f-droid repo is not possible at all, because they only include fully FOSS apps.

**Comment by rugk** [comment] 2021-06-12 09:22
Yes, It would be great to see this Android app on F-Droid!

[F-Droid](https://f-droid.org/) is an Android app store specifically for free/libre open-source apps. It would be great if your app could be released there, as it is the number one for getting FLOSS Android apps for many people.
F-Droid also builds all apps from source ([optionally even reproducible](https://f-droid.org/en/docs/Reproducible_Builds/)), so downloads from there can be trusted.

The [app developer FAQ](https://f-droid.org/en/docs/FAQ_-_App_Developers/) or [the quick start guide](https://f-droid.org/en/docs/Submitting_to_F-Droid_Quick_Start_Guide/) may help you to get started.

BTW a release on F-Droid could also bring some (more) popularity (in case that is intended), as it will show up in the app (new apps are featured there).

Backlink to the CWA discussion with more information on that: https://github.com/corona-warn-app/cwa-app-android/issues/1483
And here is the discussion about the corresponding EU app: https://github.com/eu-digital-green-certificates/dgca-wallet-app-android/issues/50

**Comment by jugendhacker** [comment] 2021-08-13 12:41
As @jleufgen just closed the Issue in the Android specific repo about this topic as duplicate of this one here, I would be interested to know if IBM/RKI did decided anything more than just flagging it as duplicate?

**Comment by jleufgen** [comment] 2021-08-17 08:14
Hello, it was decided against the publication, maintenance and community support of an f-droid version. Best regards

**Closed by jleufgen** 2021-08-17 08:14 UTC

**Comment by ilf** [comment] 2021-08-17 08:17
What are the reasons to deny this?

Can the community do it themselves?

**Comment by jugendhacker** [comment] 2021-08-17 08:26
@ilf the license allows it, so yeah we could do it as community, but I would suggest to discuss anything further over at the [corresponding merge request](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/9360) at the fdroiddata repo.

**Comment by Jowat97** [comment] 2021-08-17 13:56
> Hello, it was decided against the publication, maintenance and community support of an f-droid version. Best regards

The CovPass App was commissioned by the federal government of Germany and funded by the public. The App itself was released under free license. How can it than be, that I have to register to an Google Account and use proprietary libraries, to use this App? Especially, since this App is required to participate a normal life again. Because a person does not want to use Google services, the person should be excluded from public life?
Decisions like this, without any kind of justification will result in fewer people using the app and less trust in governmental institutions.

I really hope, that the F-Droid maintainer will proceed with the inclusion, since this App was released under Apache 2.0 License: `You may reproduce and distribute copies of the Work or Derivative Works thereof in any medium, with or without modifications, and in Source or Object form.`
So there should be no legal issues whatsoever.

A publicly funded app, released under a free license should be free and public as well.

**Comment by zak333** [comment] 2021-08-17 19:03
> Hello, it was decided against the publication, maintenance and community support of an f-droid version. Best regards

Hello.
There are people out there offering publication, maintenance and community support **for free** with no conditions or strict requirements asked for. More than 50 people upvoted the [other issue](https://github.com/Digitaler-Impfnachweis/covpass-android/issues/2) and almost 30 people upvoted this one.

Now after 2 months all you are giving is a short one-liner rejecting all the above without even an explanation.

Do you really have your users in mind when working for the public receiving our public money?

The reaction to this request for sure seems like you don't even care at all.

**Comment by rugk** [comment] 2021-08-17 19:48
Okay, [FOI requested information about that decision](https://fragdenstaat.de/projekt/dokumente-zur-entscheidung-die-covpass-app-nicht-auerhalb-des-google-play-stores-zu-veroffentlichen/)…

**Comment by Ein-Tim** [comment] 2021-08-17 20:03
Thank you @rugk!

**Comment by jugendhacker** [comment] 2021-08-30 13:25
Just for those who might have subscribed this issue: through community work [CovPass](https://f-droid.org/de/packages/de.rki.covpass.app/) and [CovPassCheck](https://f-droid.org/de/packages/de.rki.covpass.checkapp/) did still make their way into the F-Droid store based on a fork which could be found [here](https://gitlab.com/covpass-android-foss/covpass-android/)

**Comment by s09bQ5** [comment] 2021-10-03 15:51
> Hello, it was decided against the publication, maintenance and community support of an f-droid version. Best regards

@jleufgen, who decided that? Both the Bundesministerium für Gesundheit and the Robert Koch-Institut answered to @rugk's FOI request that there never was a decision like that.

**Comment by rugk** [comment] 2021-10-03 20:00
> Both the Bundesministerium für Gesundheit and the Robert Koch-Institut answered to @rugk's FOI request that there never was a decision like that.

That is not correct to say like that. The…
* BMG answered, that there are no documents regarding such a request (that fall under FOI/IFG), i.e. it was not documented. Such a decision could e.g. still be done orally.
* RKI said, that there was no decision _not_ to release the app on F-Droid, but “the release outside of the Google Play Store was merely deprioritized and put on hold.”. As such, there are no documents regarding that.

Note the answers are also a few months old.
